package(default_visibility = ['//visibility:public'])

cc_binary(
  name = 'original',
  visibility = ['//visibility:public'],
  srcs = [
    'original.cpp',
  ],
)

cc_binary(
  name = 'new',
  visibility = ['//visibility:public'],
  srcs = [
    'new.cpp',
  ],
)
