package(default_visibility = ['//visibility:public'])

cc_binary(
  name = 'license',
  visibility = ['//visibility:public'],
  srcs = [
    'license.cpp',
  ],
)

cc_binary(
  name = 'license_key',
  visibility = ['//visibility:public'],
  srcs = [
    'license_key.cpp',
  ],
)
