package(default_visibility = ['//visibility:public'])

cc_binary(
  name = 'rats',
  visibility = ['//visibility:public'],
  srcs = [
    'rats.cpp',
  ],
  copts = [
    '-Wno-unused-const-variable',
    '-Wno-unused-parameter',
    '-Wno-unused-private-field',
  ],
)
