package(default_visibility = ['//visibility:public'])

cc_binary(
  name = 'original',
  visibility = ['//visibility:public'],
  srcs = [
    'original.cpp',
  ],
)

cc_binary(
  name = 'logic_error',
  visibility = ['//visibility:public'],
  srcs = [
    'logic_error.cpp',
  ],
)

cc_binary(
  name = 'compile_error',
  visibility = ['//visibility:public'],
  srcs = [
    'compile_error.cpp',
  ],
)
